spring:
  application:
    name: lucky-backend
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
              - birthyear
              - talk_message

  datasource:
    driver-class-name: ${db.driver-class-name}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        debug: true
        smtp:
          auth: ${mail.auth}
          starttls:
            enable: ${mail.enable}

  config:
    import: db.yml
  jpa:
    hibernate:
      ddl-auto: update
    #create : Delete an existing table and recreate it
    #create-drop : Same as 'create' but table drop at the end of the session
    #update : Reflect changes only
    #validate : Check the object configuration and schema mapping
    #none : Doing nothing
    #?? ?? : validate, none (? ?? ??? ???? ?????? ???? ??)
    #?? ?? : create, create-drop, update
    #??? : update, validate

    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql