spring:
  application:
    name: lucky-backend
  datasource:
    driver-class-name: ${db.driver-class-name}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  config:
    import: db.yml
  jpa:
    hibernate:
      ddl-auto: update
    #create : Delete an existing table and recreate it
    #create-drop : Same as 'create' but table drop at the end of the session
    #update : Reflect changes only
    #validate : Check the object configuration and schema mapping
    #none : Doing nothing
    #?? ?? : validate, none (? ?? ??? ???? ?????? ???? ??)
    #?? ?? : create, create-drop, update
    #??? : update, validate

    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql